# Setup color scheme <brokenman> for list call
alias ll='/bin/ls --color=auto -lF'
alias la='/bin/ls --color=auto -axF'
alias ls='/bin/ls --color=auto -xFpt'
alias l='ls'
alias lt='ls | head '
alias ld='ls -d */'
alias lc='ls | wc -l'
alias neomutt='TERM=xterm neomutt'
alias vifm='TERM=xterm vifm'
alias nnn='TERM=xterm nnn'
alias wavemon="TERM=xterm wavemon"
alias cls='clear'
alias cs='clear;ls'
alias df='df -hT -x squashfs'
alias pg='ps aux | grep'
alias sudox="sudo chmod u+x"
alias pingg='ping -c 10 google.com'
alias wget='wget -c'
alias word='sdcv'
alias sc='sc-im'
alias ytdl='youtube-dl --no-playlist -cit'
alias yta='youtube-dl --extract-audio --audio-format mp3'
alias gcal='gcalcli' #'gcalcli --nocache'
alias calw='gcal calw --monday today'
alias telegram-cli='telegram-cli -N'
alias link="watch -n1 '/sbin/iwconfig wlan0 | grep -i quality'"
alias lynx="lynx -accept-all-cookies"
alias fehs='feh --start-at'
alias chromium-browser='chromium-browser --password-store=basic %U' #--incognito
alias config="/usr/bin/git --git-dir=$HOME/.myconf.git --work-tree=$HOME"
alias gs="git status -uno"
alias gc='git commit -m '
alias event='gcalcli --default-calendar linna.kkpp@gmail.com quick'
alias fd='fdfind'
alias open='xdg-open "$(fzf)"'
alias fmusic='mpv "$(fzf)"'
alias tc='telegram-cli -N'
alias mpvm='mpv --shuffle'
alias diff='diff --color'
alias mem='watch -n1 ls-mem'
alias tracktime='time cat'
alias cleaname="perl-rename 's/[ \(\)]/_/g;'"
alias rf='ranger'
alias play='mpv "$(fzf)"'
alias vf='vim $(fzf)'
alias goto='cd $(fzf)'
alias vb='/usr/bin/vim .bashrc'
alias dr='cd "$HOME/Dropbox/drafts"'
alias lv='ls | less'
alias dt='vim $(date +%Y.%m.%d.md)'
alias docs='cat $HOME/Dropbox/drafts/details.md | ag'
alias inoreader='newsboat -C $HOME/.config/newsboat/inoconfig'
alias weather='curl wttr.in'
