# Setup color scheme <brokenman> for list call
alias ll='/bin/ls --color=auto -lF'
alias la='/bin/ls --color=auto -axF'
alias ls='/bin/ls --color=auto -xFpt'
alias l='ls'
alias lt='ls | head '
alias ld='ls -d */'
alias lc='ls | wc -l'
alias cls='clear'
alias clr='clear;ls'
alias df='df -hT -x squashfs'
alias pg='ps aux | grep'
alias sudox="sudo chmod u+x"
alias pingg='ping -c 10 google.com'
alias wget='wget -c -U "mozilla"'
alias mpv='mpv --no-audio-display'
alias word='sdcv'
alias sc='sc-im'
alias ytdl='youtube-dl --no-playlist -cit'
alias ytdlm='youtube-dl --extract-audio --audio-format mp3'
alias gcal='gcalcli' #'gcalcli --nocache'
alias calw='gcal calw --monday today'
alias telegram-cli='telegram-cli -N'
alias link="watch -n1 '/sbin/iwconfig wlan0 | grep -i quality'"
alias lynx="lynx -accept-all-cookies"
alias fehs='feh --start-at'
alias chromium-browser='chromium-browser --password-store=basic %U' #--incognito
alias config='/usr/bin/git --git-dir=/home/guest/.myconf/ --work-tree=/home/guest/'
alias gs="git status -uno"
alias gc='git commit -m '
alias diary='vim "`date +%F`".md'
alias event='gcalcli --default-calendar linna.kkpp@gmail.com quick'
alias neomutt='TERM=xterm neomutt'
alias fd='fdfind'
alias open='xdg-open "$(fzf)"'
alias fmusic='mpv "$(fzf)"'
alias tc='telegram-cli -N'
alias mpvm='mpv --shuffle'
alias evince='atril'
alias eog='eom'
alias diff='diff --color'
alias vifm='TERM=xterm vifm'
alias nnn='TERM=xterm nnn'
alias mem='watch -n1 ls-mem'
alias tracktime='time cat'
alias cleaname="perl-rename 's/[ \(\)]/_/g;'"
