# Setup color scheme <brokenman> for list call
alias ll='/bin/ls --color=auto -lF'
alias la='/bin/ls --color=auto -axF'
alias ls='/bin/ls --color=auto -xFpt'
alias l='ls'
alias lt='ls -1 | head '
alias ld='ls -d */'
alias lc='ls | wc -l'
alias neomutt='TERM=xterm neomutt'
alias vifm='TERM=xterm vifm'
alias nnn='TERM=xterm nnn'
alias wavemon="TERM=xterm wavemon"
alias cls='clear'
alias cs='clear;ls'
alias df='df -hT -x squashfs'
alias pg='ps aux | grep'
alias sudox="sudo chmod u+x"
alias pingg='ping -c 10 google.com'
alias wget='wget -c'
alias word='sdcv -c -u "Concise Oxford English Dictionary (En-En)" -u "Urban Dictionary P1 (En-En)" -u "Urban Dictionary P2 (En-En)"'
alias sc='sc-im'
alias ytdl='youtube-dl'
alias ytp='youtube-dl --download-archive downloaded.txt'
alias yta='youtube-dl --extract-audio --audio-format mp3'
alias gcal='gcalcli' #'gcalcli --nocache'
alias calw='gcal calw --monday today'
alias telegram-cli='telegram-cli -N'
alias link="watch -n1 '/sbin/iwconfig wlan0 | grep -i quality'"
alias lynx="lynx -accept-all-cookies"
alias fehs='feh --start-at'
alias chromium-browser='chromium-browser --password-store=basic %U' #--incognito
alias config="/usr/bin/git --git-dir=$HOME/.myconf.git --work-tree=$HOME"
alias gs="git status -uno"
alias gc='git commit -m '
alias gd='git diff'
alias event='gcalcli --default-calendar linna.kkpp@gmail.com quick'
alias open='xdg-open "$(fzf)"'
alias fmusic='mpv "$(fzf)"'
alias tc='telegram-cli -N'
alias mpvm='mpv --shuffle'
alias diff='diff --color'
alias mem='watch -n1 ls-mem'
alias tracktime='time cat'
alias rf='ranger'
alias vf='vim $(fzf)'
alias goto='cd $(fzf)'
alias lv='ls | less'
alias dt='vim $(date +%Y.%m.%d.md)'
alias docs='cat $HOME/Dropbox/drafts/details.md | ag'
alias inoreader='newsboat -C $HOME/.config/newsboat/inoconfig'
alias altreader='newsboat -C $HOME/.config/altreader/config -u $HOME/.config/altreader/urls '
alias weather='curl wttr.in'
alias zo='zathura "$(find . -iname '*.pdf'| fzf)"'
alias gcal-add='gcalcli --default-calendar linna.kkpp@gmail.com quick'
alias sb='source ~/.bash_profile'
alias ag='ag --hidden'
alias ts="todo.sh -ad $HOME/.todo/someday.conf"
alias tm="todo.sh -ad $HOME/.todo/maybe.conf"
alias to="todo.sh -ad $HOME/.todo/trello.conf"
alias ch='cheat -e'
alias dwn='sudo xbacklight -dec 5'
alias up='sudo xbacklight -inc 5'
alias urban='sdcv -c -u "Urban Dictionary P1 (En-En)" -u "Urban Dictionary P2 (En-En)"'
alias nct='nctelegram'
alias vi='vim'
alias b='buku'
alias mplay='mpv "$(fzf)"'
alias vis='sudo EDITOR=vim visudo'
alias tc1='truecrypt --mount /mnt/sda4/Linn/small.crypt /media/truecrypt1'
#alias pi='sudo pacman -S'
alias calsync=' CALCURSE_CALDAV_PASSWORD=$(pass show tech/nextcloud | head -1) calcurse-caldav'
alias wt='workon tf15'
alias pac='sudo pacman -Syu'
alias vimwiki='vim -c VimwikiIndex'
alias view='sxiv -r -t *'
alias bm='bashmount'
alias dropbox='dropbox-cli'
alias tlmgr='/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode'
alias sx='sxiv'
